### ISSUE TITLE
How to use updated Splunk version?

### ISSUE THREAD

**Issue by davpx** [splunk/splunk-aws-cloudformation#11]
I've tried hacking up the templates a bit and redirected all s3 links to my own and copied the cookbooks.tar.gz and roles.tar.gz from the splunk-cloud bucket. I modified versions.rb within attributes to use the most current version of Splunk and zipped the package back up and uploaded to my s3 bucket. I can confirm the archives are publicly available and downloadable without issue however I receive "failed to run run chef-solo" upon the first instance creation. Any suggestions?

**Comment by rarsan** [comment]
Assuming you updated both the version and corresponding server build number, the steps you have taken are correct. However, it turns out recent Splunk version will return error when changing admin password to the same default, "changeme" (if attribute not modified in default.rb). This will cause the chef run to fail. The recipe was updated to fix this issue and cookbooks.tar.gz + roles.tar.gz have been updated in S3. Please let me know if you still encounter that error. Hope this answers your question.

**Comment by davpx** [comment]
Works beautifully. Thanks!

**Comment by rarsan** [comment]
My pleasure.

**Comment by davpx** [comment]
Hey Roy it's me again,

So I really want to keep in line with the provided cookbooks but I notice that they're using a different replication port than normal and we dont always get the most up to date splunk version. I also noticed today whilst deploying a new project that the cf template fails on gem install chef with no changes made to it. How do we work to keep this thing up to date and working for all? I'd be glad to contribute anywhere you think yo need assistance even it if simply updating the version numbers and builds.

**Comment by rarsan** [comment]
Re setting splunk version, changing splunk replication port, or any splunk configuration for that matter, all this can be controlled via attributes set in roles. I think you've already done that by hosting your own copy of roles.tar.gz. Having said that, in Chef best practices, users commonly own & manage their own chef repo, particularly by updating roles and environments to fit their requirements. Therefore, I'm actively consolidating all these configuration files into a minimal version-controlled chef repo that users can fork/modify and directly reference from their splunk cfn templates. This should help with configurability & extensibility by eliminating the need for user to manage & host their own roles.tar.gz. Stay tuned!

Re template failure on gem install chef:
You're touching on the important tradeoff between boot-time configuration and fully baked AMI.
Each has their own pros & cons. Fully baked AMIs provides reliability, fast deployment speed but limits flexibility and adds some complexity to manage their lifecycle. On the other hand, boot-time configuration (using cfn/chef/puppet/ansible/etc.) are simple, readable & customizable, but adds deployment latency and subject to third party outages, e.g. github/npm/gem hosting service as you've probably encountered. For those reasons, some users opt to package and reference their own custom AMIs from their splunk cfn templates.
Since I contribute to this project on my free time, I haven't had the time to provide partially-baked AMIs with all dependencies installed and packages downloaded (including splunk binaries). It would still run chef configuration at boot time using user-provided roles/environments, thereby getting best of both worlds. A simple Packer (https://www.packer.io/) template can achieve this, and build new AMIs with every new Splunk version, and cfn templates would be updated to reference new AMI. What do you think? Are you interested in helping out with that?

**Comment by davpx** [comment]
It does indeed sound interesting. Sorry for the delay by the way. Still recovering from .conf. So just to be clear, does the AMI need a Splunk rpm pre-installed? I assume not as it seems chef is doing quite a bit of the work. Is the goal to maintain a reference AMI with just the needed dependencies and keep the cfn template up to date? If so I think I can certainly assist in that. Shall we work out a time to have a short conference to sync up?

**Comment by rarsan** [comment]
Smooth recovery!
Yes, that would be great! Let's discuss it some more. Please feel free to reach me at rarsan [@] splunk.com

**Comment by davpx** [comment]
Closing this down. Finally getting back to this and looks to have evolved a lot.
